#!/usr/bin/env python3
"""Generate a reset-state file from StandbyController.default_position.

Places the robot at the *exact* standby default pose, upright, and uses forward
kinematics to drop the pelvis so the lowest foot collision geom just touches the
floor. Writes the clean pose as a `softtouch_mujoco_reset_state_v1` file the
dribble sims can load via --reset (no PD settle -> joint_pos stays = default).

  ~/miniconda3/envs/multiagentsim/bin/python tools/make_standby_reset.py
"""
import numpy as np
import mujoco

MJCF = "/home/aldebaran/Desktop/dribbling_controller/mjcf/g1_softtouch_dribble.xml"
OUT = "/home/aldebaran/Desktop/dribbling_controller/config/g1/softtouch_mujoco_reset_standby.txt"

# StandbyController joint_names / default_position / kp / kd
# (config/g1/softtouch_dribble_controllers.yaml standby_controller block).
JOINTS = [
    "left_hip_pitch_joint", "left_hip_roll_joint", "left_hip_yaw_joint",
    "left_knee_joint", "left_ankle_pitch_joint", "left_ankle_roll_joint",
    "right_hip_pitch_joint", "right_hip_roll_joint", "right_hip_yaw_joint",
    "right_knee_joint", "right_ankle_pitch_joint", "right_ankle_roll_joint",
    "waist_yaw_joint", "waist_roll_joint", "waist_pitch_joint",
    "left_shoulder_pitch_joint", "left_shoulder_roll_joint", "left_shoulder_yaw_joint",
    "left_elbow_joint", "left_wrist_roll_joint", "left_wrist_pitch_joint", "left_wrist_yaw_joint",
    "right_shoulder_pitch_joint", "right_shoulder_roll_joint", "right_shoulder_yaw_joint",
    "right_elbow_joint", "right_wrist_roll_joint", "right_wrist_pitch_joint", "right_wrist_yaw_joint",
]
DEFAULT_Q = np.array([
    -0.312, 0.0, 0.0, 0.669, -0.33, 0.0,
    -0.312, 0.0, 0.0, 0.669, -0.33, 0.0,
    0.0, 0.0, 0.0,
    0.2, 0.2, 0.0, 0.6, 0.0, 0.0, 0.0,
    0.2, -0.2, 0.0, 0.6, 0.0, 0.0, 0.0,
])
BALL_FORWARD_M = 0.65
BALL_Z_M = 0.10
START_Z = 0.90          # arbitrary; FK then drops the pelvis to put feet on the floor
GROUND_CLEARANCE = 0.001


def main():
    model = mujoco.MjModel.from_xml_path(MJCF)
    data = mujoco.MjData(model)

    nid = lambda t, nm: mujoco.mj_name2id(model, t, nm)
    qadr = np.array([model.jnt_qposadr[nid(mujoco.mjtObj.mjOBJ_JOINT, n)] for n in JOINTS])

    bj = nid(mujoco.mjtObj.mjOBJ_JOINT, "floating_base_joint")
    bq = model.jnt_qposadr[bj]
    balj = nid(mujoco.mjtObj.mjOBJ_JOINT, "softtouch_ball_freejoint")
    ballq = model.jnt_qposadr[balj]

    # foot collision geoms (capsules, size[0] = radius) -> use to find the floor drop
    foot_geoms = [g for g in range(model.ngeom)
                  if (mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, g) or "").endswith("_collision")
                  and "foot" in (mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, g) or "")]
    assert foot_geoms, "no foot collision geoms found"

    mujoco.mj_resetData(model, data)
    data.qpos[bq:bq + 3] = [0.0, 0.0, START_Z]
    data.qpos[bq + 3:bq + 7] = [1.0, 0.0, 0.0, 0.0]
    data.qpos[qadr] = DEFAULT_Q
    mujoco.mj_forward(model, data)

    # lowest extent of any foot capsule = center_z - radius
    foot_bottom = min(data.geom_xpos[g][2] - model.geom_size[g][0] for g in foot_geoms)
    drop = foot_bottom - GROUND_CLEARANCE
    print(f"[fk] foot_bottom={foot_bottom:.4f}  ->  pelvis_z={START_Z - drop:.4f}")

    root_pos = np.array([0.0, 0.0, START_Z - drop])
    root_quat = np.array([1.0, 0.0, 0.0, 0.0])
    settled_q = DEFAULT_Q.copy()

    # ball straight ahead in world +x at the configured dribble height
    ball_pos = [root_pos[0] + BALL_FORWARD_M, root_pos[1], BALL_Z_M]

    def row(name, vals):
        return name + " " + " ".join(repr(float(v)) for v in vals)

    lines = [
        "# softtouch_mujoco_reset_state_v1",
        "# generated by tools/make_standby_reset.py from StandbyController.default_position",
        "source_policy standby_default_position",
        "motion_frame -1",
        "target_yaw_deg 0",
        "joint_noise 0",
        "root_joint floating_base_joint",
        "ball_joint softtouch_ball_freejoint",
        row("root_pos", root_pos),
        row("root_quat", root_quat),
        "root_lin_vel 0 0 0",
        "root_ang_vel_body 0 0 0",
        row("ball_pos", ball_pos),
        "ball_quat 1 0 0 0",
        "ball_lin_vel 0 0 0",
        "ball_ang_vel 0 0 0",
        "joint_names " + " ".join(JOINTS),
        row("joint_pos", settled_q),
        "joint_vel " + " ".join(["0"] * len(JOINTS)),
    ]
    with open(OUT, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"[done] wrote {OUT}")


if __name__ == "__main__":
    main()
